controller_list:
  - name: fake_xarm_controller
    type: $(arg execution_type)
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - gripper_1_joint
initial:  # Define initial robot poses.
  - group: xarm
    pose: Home
  - group: gripper
    pose: Close_gripper
