# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_1_joint:
    has_velocity_limits: true  # 是否启用速度限制
    max_velocity: 0.35  # 最大速度 min_velocity
    has_acceleration_limits: false  # 是否启用加速度限制
    max_acceleration: 0  # min_acceleration
  arm_2_joint:
    has_velocity_limits: true
    max_velocity: 0.35
    has_acceleration_limits: false
    max_acceleration: 0
  arm_3_joint:
    has_velocity_limits: true
    max_velocity: 0.35
    has_acceleration_limits: false
    max_acceleration: 0
  arm_4_joint:
    has_velocity_limits: true
    max_velocity: 0.35
    has_acceleration_limits: false
    max_acceleration: 0
  arm_5_joint:
    has_velocity_limits: true
    max_velocity: 0.35
    has_acceleration_limits: false
    max_acceleration: 0
  arm_6_joint:
    has_velocity_limits: true
    max_velocity: 0.35
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_1_joint:
    has_velocity_limits: true
    max_velocity: 0.35
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_2_joint:
    has_velocity_limits: true
    max_velocity: 0.35
    has_acceleration_limits: false
    max_acceleration: 0
