xarm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin  # 运动学求解器插件名称
  kinematics_solver_search_resolution: 0.005  # 计算逆运动学时，指定在冗余度空间里搜索时的分辨率
  kinematics_solver_timeout: 0.005  # 每次迭代计算的超时时间